test_maker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from quiz import views as quiz_views
from maker import views as maker_views
from taker import views as taker_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', maker_views.index, name='index'),
    path('register/', maker_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('quiz-list/', quiz_views.QuizListView.as_view(), name='quiz-list'),

    path('quiz/<int:pk>/', quiz_views.QuizDetailView.as_view(), name='quiz-detail'),
    path('quiz/<int:pk>/update/', quiz_views.updateQuiz, name='quiz-update'),
    path('quiz/<int:pk>/delete/',
         quiz_views.QuizDeleteView.as_view(), name='quiz-delete'),
    path('quiz/new/', quiz_views.newQuiz, name='new-quiz'),
    path('quiz/<int:pk>/duplicate/',
         quiz_views.quizDuplicate, name='quiz-duplicate'),
    path('quiz/<int:pk>/result/', quiz_views.quizResult, name='quiz-result'),







    path('take-quiz/<int:pk>/register/',
         taker_views.takeQuizRegister, name='take-quiz-register'),
    path('take-quiz/<int:pk>/<int:taker_id>/',
         taker_views.takeQuiz, name='take-quiz'),
    path('take-quiz/<int:pk>/<int:taker_id>/submit/',
         taker_views.submitQuiz, name='submit-quiz'),
    path('take-quiz/<int:pk>/<int:taker_id>/result/',
         taker_views.result, name='result'),

    path('Exportstudent/take-quiz/<int:pk>/<int:taker_id>/result/',
         taker_views.Export_resultlist, name='result'),

    path('answer_overview/', taker_views.resultbloom, name='result_bloom'),
    path('Exportstudent/quiz/<int:pk>/result/',
         quiz_views.Export_resultlist, name="exportresultlist"),
    # path('Exportexcel/', quiz_views.export_excel, name="exportexcel"),
    # path('Exportpdf/', quiz_views.export_pdf, name="exportpdf"),
]

quiz/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import datetime, timedelta
import pytz


class Quiz(models.Model):
    maker = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    startDateTime = models.DateTimeField(null=True)
    timeLimit = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("quiz-detail", kwargs={"pk": self.pk})
        # return reverse("quiz-detail", pk=self.pk)

    @property
    def endDateTime(self):
        return self.startDateTime + timedelta(minutes=self.timeLimit)

    def hasStarted(self):
        now = datetime.now().replace(tzinfo=pytz.UTC)
        return now > self.startDateTime

    def isOver(self):
        now = datetime.now().replace(tzinfo=pytz.UTC)
        return now >= self.endDateTime

    def getStartDate(self, dateFormat='%Y-%m-%d'):
        startDateTime = self.startDateTime

        if startDateTime is not None:
            startDate = startDateTime.date().strftime(dateFormat)
        else:
            startDate = None

        return startDate

    def getStartTime(self, timeFormat='%H:%M'):
        startDateTime = self.startDateTime

        if startDateTime is not None:
            startTime = startDateTime.time().strftime(timeFormat)
        else:
            startTime = None

        return startTime

    @property
    def totalPoints(self):
        return sum(question.point for question in self.question_set.all())


class QuestionManager(models.Manager):
    def mcq_questions(self):
        return self.get_queryset().filter(type='mcq')

    def checkbox_questions(self):
        return self.get_queryset().filter(type='checkbox')

    def short_questions(self):
        return self.get_queryset().filter(type='short')


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=500)
    typequestion = models.CharField(max_length=500)
    point = models.IntegerField()
    type = models.CharField(max_length=20, null=True)

    objects = QuestionManager()

    def __str__(self):
        return str(self.question)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=500)

    def __str__(self):
        return str(self.choice)


class McqAnswer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    answer = models.IntegerField()

    def __str__(self):
        return str(self.answer)


class CheckboxAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.IntegerField()

    def __str__(self):
        return str(self.answer)


class ShortAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return str(self.answer)

 
    

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.exceptions import PermissionDenied
from .models import Quiz
from quiz.utils.createQuiz import createQuiz
from quiz.utils.updateQuiz import _updateQuiz
from quiz.utils.duplicateQuiz import duplicateQuiz

import datetime
import csv
import xlwt
from django.template.loader import get_template
from xhtml2pdf import pisa
from taker.models import Taker


class QuizDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Quiz

    def test_func(self):
        return self.request.user == self.get_object().maker


class QuizListView(LoginRequiredMixin, ListView):
    model = Quiz

    def get_queryset(self):
        return Quiz.objects.filter(maker=self.request.user).order_by('-id')
    # paginate_by = 100


class QuizDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Quiz
    success_url = reverse_lazy('quiz-list')

    def test_func(self):
        return self.request.user == self.get_object().maker


@login_required
def newQuiz(request):
    if request.method == 'POST':
        data = request.POST.dict()
        print(data)

        createQuiz(data, request.user)

        return redirect('quiz-list')

    defaultNumberOfChoices = range(1, 5)
    return render(request, 'quiz/new_quiz.html', {'defaultNumberOfChoices': defaultNumberOfChoices})


@login_required
def updateQuiz(request, pk):
    quiz = get_object_or_404(Quiz, id=pk)

    if request.user != quiz.maker:
        raise PermissionDenied

    if request.method == 'POST':
        data = request.POST.dict()
        print(data)
        _updateQuiz(data, quiz)

        return redirect('quiz-list')

    startDate = quiz.getStartDate()
    startTime = quiz.getStartTime()

    return render(request, 'quiz/quiz_update.html', {'quiz': quiz, 'startDate': startDate, 'startTime': startTime})


@require_POST
def quizDuplicate(request, pk):
    parentQuiz = get_object_or_404(Quiz, id=pk)

    if request.user != parentQuiz.maker:
        raise PermissionDenied

    data = request.POST.dict()

    quiz = duplicateQuiz(request.user, parentQuiz, data['quiz'])

    return redirect('quiz-update', pk=quiz.id)


@login_required
def quizResult(request, pk):
    quiz = get_object_or_404(Quiz, id=pk)

    if request.user != quiz.maker:
        raise PermissionDenied

    takers = quiz.taker_set.all()
    return render(request, 'quiz/result.html', {'quiz': quiz, 'takers': takers, 'pk': pk})


def Export_resultlist(request, pk):
    quiz = get_object_or_404(Quiz, id=pk)
    response=HttpResponse(content_type="apllication/ms-excel")
    response["content-Disposition"]='attachment ; filename=Takers'+str(datetime.datetime.now())+'.xls'
    workbook=xlwt.Workbook(encoding='utf-8')
    worksheet=workbook.add_sheet("Takers")
    columns=['ชื่อ' , 'email' , 'คะแนน'  ]
    rownumber=0
    for col in range(len(columns)):
        worksheet.write(rownumber , col , columns[col])
    takers = quiz.taker_set.all()
    for std in takers:
        rownumber = rownumber + 1 
        print(rownumber)
        columns = [std.name,std.email,std.score]
        for col in range(len(columns)):
            print(col)
            worksheet.write(rownumber , col , columns[col])

    
    workbook.save(response)    
    return response

quiz/templates/quiz/3dot_menu.html
 <!--หน้าเมนูสำหรับการแสดงผล-->
 
<div class="more">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-three-dots-vertical"
        viewBox="0 0 16 16">
        <path
            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
    </svg>
    <div class="more-menu">
        <div class="more-menu-caret">
            <div class="more-menu-caret-outer"></div>
            <div class="more-menu-caret-inner"></div>
        </div>

        <ul class="more-menu-items" tabindex="-1" role="menu" aria-labelledby="more-btn" aria-hidden="true">
            
            <li class="more-menu-item" role="presentation">
                <form action="{% url 'quiz-result' quiz.id %}">
                    <button type="submit" class="more-menu-btn" role="menuitem" id='resultBtn'>คำตอบ</button>
                </form>
            </li>

            <li class="more-menu-item" role="presentation">
                <button type="button" class="more-menu-btn" role="menuitem" data-toggle="confirm"
                    data-id="{{quiz.id}}">ลบ</button>
            </li>

            <li class="more-menu-item" role="presentation">
                <button type="button" class="more-menu-btn duplicate" role="menuitem" data-toggle="modal"
                    data-target="#duplicateModal" data-id='{{quiz.id}}'>ทำสำเนา</button>
            </li>

        </ul>
    </div>
</div>

quiz/templates/quiz/duplicate_modal.html
{% load static %}
<div class="modal fade" id="duplicateModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">สร้างแบบทดสอบใหม่</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <form id='duplicate_form' method="POST">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">ชื่อแบบทดสอบที่จะสร้างใหม่</label>
                        <input type="text" class="form-control" name='quiz' value='{{quiz.name}}' required autofocus>
                        <button id='submit' type='submit' hidden></button>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button id='duplicateDone' type="button" class="btn btn-primary">ต่อไป</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">ยกเลิก</button>
            </div>
            
        </div>
    </div>
</div>
<script src="{% static 'quiz/duplicate_quiz.js' %}"></script>

quiz/templates/quiz/navbar.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="http://www.example.com" />

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class=" navbar-brand" href="#">Qu-mative</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            
            <a href="{% url 'logout' %}" >logout</a>
            <!-- <li class="nav-item active">
                <a class="nav-link" href="{%url 'quiz-list'%}">Quizzes<span class="sr-only">(current)</span></a>
            </li> -->
        </ul>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script src="https://apis.google.com/js/platform.js"></script>

quiz/templates/quiz/new_quiz.html
{% extends 'quiz/new_update_quiz_common.html' %}
{% load static %}

{% block content %}
<div class="container">

    <form action='{% url "new-quiz" %}' method='post' class="quiz-form">
        {% csrf_token %}

        {% include 'quiz/settings_modal.html' %}

        <div class="heading">
            
            <input type='text' class="heading__text" name='quiz' required autofocus placeholder="ชื่อวิชา">
            <a href="{{quiz.get_absolute_url}}" class="card-link">มุมมอง</a>    
        </div>

  
 
        <button type='submit' id='submit' hidden></button>

    </form>
</div>

{% endblock content %}

quiz/templates/quiz/new_quiz_choices.html
{%for i in defaultNumberOfChoices %}

    <div class="quiz-form__ans">
        
        <input type="radio" name='1_radio_option' value='{{i}}' required>
        <span class="design"></span>

        <input type="text" name="1_option{{i}}" placeholder="เพิ่มตัวเลือก {{i}}" required>
        <svg fill="#5c626f" class="delete_mcq_choice delete_choice" xmlns="http://www.w3.org/2000/svg"
            width="24" height="24" viewBox="0 0 24 24">
            
            <path
                d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
            </path>

            <path d="M0 0h24v24H0z" fill="none"></path>
        </svg>
    </div>

{% endfor %}

<div class="quiz-form__ans">
    <input type="radio">
    <span class="design"></span>
    <input type="text" class='add_mcq_choice' placeholder="เพิ่มตัวเลือก">
</div>

quiz/templates/quiz/new_update_quiz_common.html
<!--หน้าเทมเพลตสร้างควิช-->

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

    <link rel="stylesheet" href="{% static 'quiz/new_quiz.css' %}">
    <link rel="stylesheet" href="{% static 'quiz/settings_modal.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <button type="button" class="btns" data-toggle="modal" data-target="#settingsModal">
          ตั้งค่า
        </button>
    </header>


    <footer class="footerbtn">

        <div class="btn-group dropup">
            <button type="button" id='add' class="btn btn-primary add_new">
                เพิ่ม 
            </button>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                 <button id='addCheckbox' class="dropdown-item"> </button>  
                <button id='addShort' class="dropdown-item">แบบเติมคำ</button>
                <button id='addMcq' class="dropdown-item">แบบเลือกตอบ</button>
            </div>
        </div>

        <button id='save' class="btns">บันทึก</button>
    </footer>



    {% block content %}


    {% endblock content %}

    <script src="{% static 'quiz/createElements.js' %}"></script>
    <script src="{% static 'quiz/add_choice.js' %}"></script>  

    <script src="{% static 'quiz/delete_choice.js' %}"></script>
    <script src="{% static 'quiz/delete_question.js' %}"></script>
    <script src="{% static 'quiz/duplicate_question.js' %}"></script>
    <script src="{% static 'quiz/settings_modal.js' %}"></script>
    <script src="{% static 'quiz/new_update_common.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="js/jquery.easydropdown.js" type="text/javascript"></script>
</body>

</html>

quiz/templates/quiz/quiz_confirm_delete.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<div class="container mt-5">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">ลบโพสต์</legend>
            <h2>คุณแน่ใจหรือว่าต้องการลบแบบทดสอบ "{{ object.name }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">ใช่ , ลบ</button>
            <a class="btn btn-outline-secondary" href="{% url 'quiz-detail' object.id %}">ยกเลิก</a>
        </div>
    </form>
</div>

quiz/templates/quiz/quiz_detail.html
{% load static %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

<link rel="stylesheet" href="{% static 'quiz/quiz_detail.css' %}">

<footer>
    <form action="{% url 'quiz-update' object.id %}" method="GET">
        <button type='submit' id='edit' class="btns"> แก้ไข </button>
    </form>
</footer>

<div class="container">
    <div class="heading">
        <h1 class="heading__text">{{object.name}}</h1>
    </div>

    <form class="quiz-form">

        {% for question in object.question_set.all %}

        {% include 'quiz/quiz_detail_common.html' %}

        {% endfor %}

    </form>

</div>

quiz/templates/quiz/quiz_detail_common.html
<div class="question">
    <div class="questionHeader">
        <p class="quiz-form__question">{{question.question}}</p>
        <!-- <p class="quiz-form__question"> {{question.typequestion}}</p> -->
        <div class="point">
            <p>{{question.point}}</p>
            {% if question.point == 1 %}
            <span>point</span>
            {% else %}
            <span>points</span>
            {% endif %}
        </div>
    </div>

    {% for choice in question.choice_set.all %}

    <label class="quiz-form__ans" for="{{forloop.parentloop.counter}}_choice{{forloop.counter}}">

        {% if question.type == 'mcq' %}

        <input type="radio" id="{{forloop.parentloop.counter}}_choice{{forloop.counter}}" required
            name='{{forloop.parentloop.counter}}_radio_option' value='{{forloop.counter}}'>

        <span class="design"></span>

        {% elif question.type == 'checkbox' %}

        <input type="checkbox" id="{{forloop.parentloop.counter}}_choice{{forloop.counter}}"
            name='{{forloop.parentloop.counter}}_checkbox_{{forloop.counter}}'>

        {% endif %}

        <span class="text">{{choice.choice}}</span>

    </label>

    {% endfor %}


    {% if question.type == 'short' %}

    <label class="quiz-form__ans">

        <input type="text" name='{{forloop.counter}}_short_1' required>

    </label>

    {%endif%}

</div>

quiz/templates/quiz/quiz_update_choices.html
{% for choice in question.choice_set.all %}

    <div class="quiz-form__ans">
        {% if question.type == 'mcq' %}

        <input type="radio" required name='{{forloop.parentloop.counter}}_radio_option'
            value='{{forloop.counter}}' 
            {% if question.mcqanswer.answer == forloop.counter %} checked {% endif %}>
        <span class="design"></span>

        {% elif question.type == 'checkbox' %}

        <input type="checkbox" name='{{forloop.parentloop.counter}}_checkbox_{{forloop.counter}}' 
        {% for answer in question.checkboxanswer_set.all %}
        {% if answer.answer == forloop.parentloop.counter%} checked {% endif %}
        {% endfor %}>

        {% endif %}

        <input type="text" required name="{{forloop.parentloop.counter}}_option{{forloop.counter}}"
            value='{{choice.choice}}'>
            
        <svg fill="#5c626f" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
        viewBox="0 0 24 24"
        class="delete_choice
        {% if question.type == 'mcq' %}
        delete_mcq_choice
        {% elif question.type == 'checkbox' %}
        delete_checkbox_choice
        {% endif %}
        ">
            <path
                d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
            </path>
            <path d="M0 0h24v24H0z" fill="none"></path>
        </svg>
    </div>

{% endfor %}

{% if question.type == 'short' %}

    {% for shortAnswer in question.shortanswer_set.all %}
        
        <div class="quiz-form__ans">

            <input type="text" name='{{forloop.parentloop.counter}}_short_{{forloop.counter}}' 
            value="{{shortAnswer.answer}}" required>

            <svg fill="#5c626f" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            viewBox="0 0 24 24"
            class="delete_choice delete_short_choice">
                <path
                    d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
                </path>
                <path d="M0 0h24v24H0z" fill="none"></path>
            </svg>

        </div>



    {% endfor %}
    
{%endif%}
        
{% if question.type == 'mcq' %}

    <div class="quiz-form__ans">
        <input type="radio">
        <span class="design"></span>
        <input type="text" class='add_mcq_choice' placeholder="เพิ่มตัวเลือก">
    </div>

{% elif question.type == 'checkbox' %}

    <div class="quiz-form__ans">
        <input type="checkbox">
        <input type="text" class='add_checkbox_choice' placeholder="เพิ่มตัวเลือก">
    </div>

{% elif question.type == 'short' %}

 

{% endif %}

 

quiz/templates/quiz/result.html
{% load static %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'quiz/result.css' %}">

<h1 class="heading__text"> ผลการทำแบบทดสอบของ {{quiz.name}}</h1>

<div class="container">
    <table class="table table-dark table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">ชื่อ</th>
                <th scope="col">อีเมลล์</th>
                <th scope="col">คะแนน</th>
                <th scope="col">แบบทดสอบ</th>
            </tr>
        </thead>
        <tbody>
            {% for taker in takers %}

            <tr>
                <td>{{taker.name}}</td>
                <td>{{taker.email}}</td>
                <td>{{taker.score}}</td>
                <td><a href="{% url 'result' quiz.id taker.id %}">ลิ้งค์</a></td>
            </tr>

            {%endfor%}
        </tbody>
    </table>
    <div align="right">
        <a href="http://127.0.0.1:8000/Exportstudent/quiz/{{pk}}/result/" class='btn btn-success'>Export Excel</a>
      
    </div>
</div>